# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache:
  packages: true

warnings_are_errors: false
r_packages:
    - remotes
    - devtools
    - tcltk2

before_install:
  - sudo add-apt-repository -y ppa:cran/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev

matrix:
  include:
  - r: release
    env:
      - FULL=true
    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: devel
  # - r: oldrel
  allow_failures:
  - r: oldrel

