# last modified 2018-12-28
# Imported from Rcmdr

globalVariables(c(
  "top", "OKCancelHelp", "ok_cancel_help", ".",

  "ActiveDataSet", "ActiveModel", "Commander", "CommanderWindow", "Factors",
  "GrabFocus", "Library", "LogWindow", "Message", "MessagesWindow", "Numeric",
  "OutputWindow", "RcmdrTclSet", "RcmdrTkmessageBox", "Species", "TwoLevelFactors",
  "Variables", "activateMenus", "activeDataSetP", "activeModel", "activeModelP",
  "add_plotVariable", "add_slide", "aes", "as_markdownCheckBox",
  "as_markdownVariable", "assoc_statsCheckBox", "assoc_statsVariable",
  "body_add_par", "body_add_table", "body_end_section_portrait", "boot", "boot.ci",
  "buttonRcmdr", "buttonsFrame", "by_groupCheckBox", "by_groupVariable",
  "by_group_Frame", "caseVariable", "case_Variable", "characterButton", "checkBoxes",
  "checkReplace", "check_locale_CheckBox", "check_locale_Variable",
  "check_locale_frame", "checkboxes_frame", "chisq_testCheckBox",
  "chisq_testVariable", "ci_mean_t", "class_Frame", "class_Variable",
  "closeCommander", "closeDialog", "colnamesVariable", "command", "conditions",
  "convert_keyVariable", "d2Button", "d3Button", "d4Button", "d5Button", "decimalFrame",
  "decimalVariable", "decreasingFrame", "decreasingVariable", "delimiterFrame",
  "delimiterVariable", "dialogSuffix", "digits_pFrame", "digits_pVariable",
  "directionFrame", "directionVariable", "dmoreButton", "do", "doItAndPrint",
  "do_testVariable", "enterKnitr", "enterMarkdown", "entry1", "errorCondition",
  "excel_sheets", "exists.method", "facet_wrap", "factor_keyVariable",
  "fisher_testCheckBox", "fisher_testVariable", "format_numbers", "fun_typeFrame",
  "fun_typeVariable", "gather_allVariable", "gather_options_frame", "getDialog",
  "getFrame", "getRcmdr", "getSelection", "gettextRcmdr", "ggplot", "group_by",
  "hide_output_Variable", "initializeDialog", "integerButton", "into_Frame",
  "into_Variable", "iris", "is.valid.name", "join_typeFrame", "join_typeVariable",
  "justDoIt", "keep_Frame", "keep_Variable", "keep_all_Button", "keep_modelVariable",
  "keep_model_inner_frame", "keep_resultsCheckBox", "keep_resultsVariable",
  "keep_selected_Button", "labelRcmdr", "labs", "listAllModels", "listDataSets",
  "listFactors", "listVariables", "locationFrame", "locationVariable", "log_txtFrame",
  "log_txtVariable", "logger", "logicalButton", "lower", "make_uniqueCheckBox",
  "make_uniqueVariable", "make_unique_frame", "method_Frame", "modifyButton",
  "mtcars", "my_palette", "na_rmVariable", "name_variable", "names_action_Frame",
  "names_action_Variable", "new_plots_windowCheckBox",
  "new_plots_windowVariable", "nominalButton", "numericButton",
  "numerical_middle_frame", "onCancel", "onDoubleClick_fun", "optionsFrame",
  "options_Frame", "options_Variable", "ordinalButton", "overwriteButton",
  "ph_with_table", "ph_with_text", "plot_in_colorsCheckBox",
  "plot_in_colorsVariable", "plot_middle_frame", "positionFrame",
  "positionVariable", "proportion", "putDialog", "putRcmdr", "quotesVariable",
  "radioButtons", "read_docx", "read_pptx", "recode_intoFrame", "recode_intoVariable",
  "regex_Variable", "regexprVariable", "removeNullRmdBlocks",
  "removeNullRnwBlocks", "replace_object", "rownamesVariable", "scope_Frame",
  "scope_Variable", "setBusyCursor", "setIdleCursor", "sides_Frame", "stat_qq_band",
  "stat_qq_line", "stat_qq_point", "subButtonsFrame", "subOKCancelHelp", "subdialog",
  "swiss", "table_typeFrame", "table_typeVariable", "testVariable", "trim.blanks",
  "trim_frame", "ungroup", "upper", "use_groups_CheckBox", "use_groups_Variable",
  "use_groups_frame", "varPosn", "variableListBox", "which_idFrame",
  "which_idVariable", "window_new_dataset_rcmdr", "x", "start", "tktag_add_obj",
  "cancelButton", "active_ds", "loadPackages", "activate_menus",
  "f3_input",

  ".Contrasts", "Dataset", "Item LibPath", "Package", "code_to_load",
  "contrastsFrame", "contrastsVariable", "do_nothing", "f2_entry_expr",
  "groupingFrame", "groupingVariable", "info", "levelNames", "levelsFrame",
  "levelsVariable", "methodFrame", "methodVariable", "pkg_ds", "pop_up_window",
  "show_output_Variable", "summary_skim", "text", "v", "var_ds_box"
))
