# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#' Rcmdr window for log transformation
#'
#' Rcmdr window for tool "ggedit"
#' @export
#' @keywords internal
#' @family plots
#'
window_ggedit <- function() {
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    initializeDialog(title = gettext_Bio("Select a `ggplot` object to modify"))
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    defaults <- list(gg_obj = NULL)

    dialog_values <- getDialog("window_ggedit", defaults)
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    upper_Frame <- tkframe(top)

    variableBox <-
        variableListBox2(upper_Frame,
                         biostat::objects_of_class("ggplot", envir = .GlobalEnv),
                         selectmode = "single",
                         title = gettext_Bio("Available objects\n (select one)"),
                         initialSelection = dialog_values$gg_obj,
                         listHeight = 4
        )
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    onOK <- function() {
        gg_obj <- getSelection(variableBox)
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        putDialog("window_ggedit", list(gg_obj = gg_obj))
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        closeDialog()
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        if (length(gg_obj) == 0) {
            errorCondition(recall = window_ggedit,
                           message = gettext_Bio("You must select a `ggplot` object"))
            return()
        }
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        # Code to call `ggedit` ==============================================
        library("ggedit")

        command1 <- glue::glue("ggedit::ggedit({gg_obj})")
        # Open ggedit:
        ggedit_obj <- eval_(command1)

        # If ggedit session is cancelled:
        if (is.null(ggedit_obj)) {
            Message("Session of `ggedit` was cancelled.", type = "warning")
            return()
        }

        # Extract and tidy up the code:
        ggedit_code <- tidy_ggedit_code(ggedit_obj)

        # Commands for Rcmdr
        command2 <- style_cmd(glue::glue("{gg_obj} + \n {ggedit_code}"))

        command <- glue::glue(
            "# --- Interactive tool `ggedit` --- \n",
            "# tidy_ggedit_code({command1})\n\n",
            "# NOTE: the following code needs to be edited manually as \n",
            "# `{gg_obj} +` should be replaced with an appropriate `ggplot2` code \n",
            "# to get a plot generated by `ggedit`. \n\n",
            command2)

        logger(command)
        # doItAndPrint(command)

        # Correct plot:
        # open_new_plots_window()
        plot(ggedit_obj)

        # ================================================================
        tkfocus(CommanderWindow())
    } # [end: onOK] ----------------------------------------------------------
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    OKCancelHelp(helpSubject = "ggedit")
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # tkgrid(labelRcmdr(top,
    #                   text = gettext_Bio("Select a `ggplot` object to modify:"),
    #                   fg = getRcmdr("title.color")),
    #        sticky = "w",
    #        pady = c(10, 0))

    tkgrid(getFrame(variableBox), sticky = "n")
    tkgrid(upper_Frame)

    tkgrid(labelRcmdr(top,
                      text = gettext_Bio('If you work in RStudio, tool `ggedit`\nwill open in "Viever" window.'),
                      fg = "darkred"),
           sticky = "s",
           pady = c(10, 0))

    # tkgrid(prefixField, sticky = "ew", columnspan = 2)
#
#     tkgrid(fun_typeFrame,
#            sticky = "w",
#            pady = c(10, 0))

    tkgrid(buttonsFrame, sticky = "ew", columnspan = 2)

    dialogSuffix(rows = 4,
                 columns = 2,
                 preventGrabFocus = TRUE)
}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
