# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#' Rcmdr window for log transformation
#'
#' Rcmdr window for tool "ggedit"
#' @export
#' @keywords internal
#' @family plots
#'
window_ggedit <- function() {
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    initializeDialog(title = gettext_Bio("Select a `ggplot` Object to Modify"))
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    defaults <- list(gg_obj = NULL)

    dialog_values <- getDialog("window_ggedit", defaults)
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    upper_Frame <- tkframe(top)

    variableBox <-
        variableListBox2(upper_Frame,
                         biostat::objects_of_class("ggplot", envir = .GlobalEnv),
                         selectmode = "single",
                         title = gettext_Bio("Available ggplot objects\n (select one)"),
                         initialSelection = dialog_values$gg_obj,
                         listHeight = 7
        )
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    onOK <- function() {
        gg_obj <- getSelection(variableBox)
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        putDialog("window_ggedit", list(gg_obj = gg_obj))
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        closeDialog()
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        if (length(gg_obj) == 0) {
            errorCondition(recall = window_ggedit,
                           message = gettext_Bio("You must select a `ggplot` object"))
            return()
        }
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        # Code to call `ggedit` ==============================================
        # Library(c("biostat", "ggedit"))
        Library("biostat")
        Library("ggedit")

        command1 <- style_cmd(glue::glue(
            "tidy_ggedit_code({{",
            "ggedit::ggedit({gg_obj}, launch.browser = TRUE,\n",
            "height = 300, width = 500)",
            "}})"
            ))
        # Open ggedit:
        ggedit_obj <- eval_(command1)

        # If ggedit session is cancelled:
        if (is.null(ggedit_obj)) {
            Message("Session of `ggedit` was cancelled.", type = "warning")
            return()
        }

        # Extract and tidy up the code:
        ggedit_code <- tidy_ggedit_code(ggedit_obj)

        # Add comments
        command1_mod <- str_replace_all(str_c("# ", command1), "\n","\n# ")

        # Commands for Rcmdr
        command2 <- style_cmd(glue::glue("{gg_obj} + \n {ggedit_code}"))

        command <- glue::glue(
            "## ------ Interactive tool `ggedit` ------ \n\n",
            "## This code opened the interactive tool `ggedit`:\n",
            "{command1_mod}\n\n",

            "## NOTE. The following code needs to be edited \n",
            "## manually as `{gg_obj} +` should be replaced \n",
            "## with an appropriate `ggplot2` code to get \n",
            "## a plot generated by `ggedit`: \n\n",
            command2)

        logger(command)
        # doItAndPrint(command)

        # Correct plot:
        # open_new_plots_window()
        plot(ggedit_obj)

        # ================================================================
        tkfocus(CommanderWindow())
    } # [end: onOK] ----------------------------------------------------------
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    OKCancelHelp(helpSubject = "ggedit")
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # tkgrid(labelRcmdr(top,
    #                   text = gettext_Bio("Select a `ggplot` object to modify:"),
    #                   fg = getRcmdr("title.color")),
    #        sticky = "w",
    #        pady = c(10, 0))

    tkgrid(getFrame(variableBox), sticky = "n")
    tkgrid(upper_Frame, columnspan = 2)

    tkgrid(labelRcmdr(
        top,
        text = gettext_Bio(glue('The tool will open in the ',
                                'default Internet browser.')),
                      fg = "darkred"),
           sticky = "s",
           pady = c(10, 2),
        columnspan = 2)

    # tkgrid(prefixField, sticky = "ew", columnspan = 2)
#
#     tkgrid(fun_typeFrame,
#            sticky = "w",
#            pady = c(10, 0))

    tkgrid(buttonsFrame, sticky = "ew", columnspan = 2)

    dialogSuffix(rows = 4,
                 columns = 2,
                 preventGrabFocus = TRUE)
}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
